# version: '3.7'

# services:
#   minio:
#     image: minio/minio:latest
#     container_name: minio
#     ports:
#       - "9000:9000"
#       - "9001:9001"
#     volumes:
#       - minio_data:/data
#     environment:
#       MINIO_ROOT_USER: minioadmin
#       MINIO_ROOT_PASSWORD: minioadmin
#       MINIO_CONSOLE_PORT: 9001
#     command: server /data

# volumes:
#   minio_data:
version: '3.7'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio1
    ports:
      - "9000:9000"    # MinIO API port
      - "9001:9001"    # MinIO Console port
    volumes:
      - D:/minio/data:/data
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: CHANGEME123
    command: server /data --console-address ":9001"

volumes:
  minio_data:
